spring:
  redis:
    database: 0
    host: 47.107.98.186
    port: 6379
  rabbitmq:
    template:
      mandatory: true
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 20
        acknowledge-mode: manual
    host: 47.107.98.186
    port: 5672
    username: admin
    password: admin
server:
  port: 8080



